# Generated by Django 4.1.6 on 2023-02-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Genre of a photo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField(help_text='The rank (priority) of the photo')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='managephotos.genre_en')),
            ],
        ),
        migrations.CreateModel(
            name='Src',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(help_text='The path to the photo', max_length=200)),
                ('url', models.URLField(help_text='Friendly URL of the photo')),
                ('src_min', models.CharField(help_text='The path to the thumbnail', max_length=200)),
                ('url_min', models.URLField(help_text='Friendly URL to the thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Title_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managephotos.keywords_en')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managephotos.photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managephotos.src'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managephotos.title_en'),
        ),
    ]
