# Generated by Django 4.1.6 on 2023-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Genre of a photo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(help_text='The path to the photo', upload_to='photo/2023/03/11/')),
                ('url', models.SlugField(blank=True, help_text='Friendly URL of the photo')),
                ('src_min', models.ImageField(help_text='The path to the thumbnail', upload_to='photo/2023/03/11/')),
                ('url_min', models.SlugField(blank=True, help_text='Friendly URL to the thumbnail')),
                ('star', models.PositiveSmallIntegerField(default=3, help_text='The rank (priority) of the photo')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('genre', models.ManyToManyField(to='managephotos.genre')),
                ('keywords', models.ManyToManyField(blank=True, to='managephotos.keywords')),
            ],
        ),
    ]
