# Generated by Django 4.1.6 on 2023-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(help_text='The path to the photo', upload_to='photo/2023/03/14/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src_min',
            field=models.ImageField(help_text='The path to the thumbnail', upload_to='photo/2023/03/14/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, help_text='Friendly URL of the photo', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url_min',
            field=models.CharField(blank=True, help_text='Friendly URL to the thumbnail', max_length=100),
        ),
    ]
