# Generated by Django 4.1.6 on 2023-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src',
            name='src',
            field=models.ImageField(help_text='The path to the photo', upload_to='photo/2023/02/13/'),
        ),
        migrations.AlterField(
            model_name='src',
            name='src_min',
            field=models.ImageField(help_text='The path to the thumbnail', upload_to='photo/2023/02/13/'),
        ),
        migrations.AlterField(
            model_name='src',
            name='url',
            field=models.URLField(blank=True, help_text='Friendly URL of the photo'),
        ),
        migrations.AlterField(
            model_name='src',
            name='url_min',
            field=models.URLField(blank=True, help_text='Friendly URL to the thumbnail'),
        ),
        migrations.AlterField(
            model_name='title_en',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
