# Generated by Django 4.1.6 on 2023-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0002_alter_src_src_alter_src_src_min_alter_src_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src',
            name='src',
            field=models.ImageField(help_text='The path to the photo', upload_to='photo/2023/02/17/'),
        ),
        migrations.AlterField(
            model_name='src',
            name='src_min',
            field=models.ImageField(help_text='The path to the thumbnail', upload_to='photo/2023/02/17/'),
        ),
        migrations.AlterField(
            model_name='src',
            name='url',
            field=models.SlugField(blank=True, help_text='Friendly URL of the photo'),
        ),
        migrations.AlterField(
            model_name='src',
            name='url_min',
            field=models.SlugField(blank=True, help_text='Friendly URL to the thumbnail'),
        ),
    ]
