# Generated by Django 4.1.6 on 2023-05-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0002_alter_photo_src_alter_photo_src_min_alter_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='photo/2023/05/30/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src_min',
            field=models.ImageField(upload_to='photo/2023/05/30/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='star',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url_min',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
