# Generated by Django 4.1.6 on 2024-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0003_alter_photo_src_alter_photo_src_min_alter_photo_star_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pubstars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('dtime', models.DateTimeField(auto_now_add=True)),
                ('star', models.PositiveSmallIntegerField()),
                ('photoid', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='photo/2024/06/23/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src_min',
            field=models.ImageField(upload_to='photo/2024/06/23/'),
        ),
    ]
