# Generated by Django 4.1.6 on 2023-02-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managephotos', '0003_alter_src_src_alter_src_src_min_alter_src_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_keyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='managephotos.keywords_en'),
        ),
        migrations.AlterField(
            model_name='src',
            name='src',
            field=models.ImageField(help_text='The path to the photo', upload_to='photo/2023/02/24/'),
        ),
        migrations.AlterField(
            model_name='src',
            name='src_min',
            field=models.ImageField(help_text='The path to the thumbnail', upload_to='photo/2023/02/24/'),
        ),
    ]
